#include "static_cast_test.cc"
#include "vector_test.cc"
#include "string_test.cc"
#include "shared_ptr_test.cc"
#include "unique_ptr_test.cc"
#include "thread_local_test.cc"
#include "CRPT_test.cc"
#include "move_test.cc"
#include "forward_test.cc"
#include "test_const/test_const.cc"
#include "function_test.cc"

// design pattern
// #include "DesignPatterns/observer_pattern_test.cc"
#include "DesignPatterns/factory_pattern_test.cc"